version: '2'

services:
    holamundo:
        container_name: holamundo
        stdin_open: true
        build:
            context: ../../builds/react
        command: npm start --host 0.0.0.0
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ../../source/holamundo:/app
        environment:
            - CHOKIDAR_USEPOLLING=true        
